#!/bin/bash

[[ $# = 5 ]] && while [ true ]; do
    # begin watching directories of interest for unwanted changes
    # inotifywait "@$SYNCDIR/$CLDPRJCT" "$SYNCDIR" "$SYNCDIR/$CLDWKSPCS" "$SYNCDIR/$CLDUSERS" \
    inotifywait "$1" "$2" "$3" "$4" -e move,create && "$5/sync50" "--delete_local_excludes"
done

exit