#!/bin/bash
readonly SYNC50PATH=$(pwd)
echo $SYNC50PATH
[[ $# = 4 ]] && while [ true ]; do
    # begin watching directories of interest for unwanted changes
    # inotifywait "@$SYNCDIR/$CLDPRJCT" "$SYNCDIR" "$SYNCDIR/$CLDWKSPCS" "$SYNCDIR/$CLDUSERS" \
    inotifywait "$1" "$2" "$3" "$4" -e move,create && echo fish #"$SYNCH50PATH/sync50" "--delete_local_excludes"
    let counter+=1
done

exit